### ISSUE TITLE
Due Date not saving for Steps

### ISSUE THREAD

**Issue by courtneyportnoy** [cmcrew/bloc-goals#1]
I see the correct due_date as part of the XHR request, but when I view my saved data the due_date for a step is not saved. The name is saved properly. Not sure if this is an API issue or an Angular issue.
http://grab.by/JVlo

**Comment by matstc** [comment]
The `due_date` parameter needs to be white listed so that ActiveRecord will save it to database.

I fixed it in [this commit](https://github.com/cmcrew/bloc-goals-api/commit/0535b1ac388b5b67955902a7bfb0a1a9459d68fb).

**Comment by courtneyportnoy** [comment]
Thanks. 

Courtney Mitchellwww.courtney-codes.comcourtney.mitchell@live.com(604) 365-7442

Date: Fri, 28 Aug 2015 10:51:22 -0700
